UXD-1878 Button group align with UI kit
acl-services/paprika pull request #1193
Opened 2021-12-01 17:32 UTC by ShanAtDiligent

### Purpose 🚀
Update Button Group font / spacing / icon to align with UI kit

### Notes ✏️
_details of code change / secondary purposes of this PR_

### Storybook 📕
http://storybooks.highbond-s3.com/paprika/UXD-1878-ButtonGroup-Align-with-UI-Kit

### Screenshots �
![Screen Shot 2021-12-01 at 9 32 24 AM](https://user-images.githubusercontent.com/92405042/144284164-ec38c17c-fa6f-457c-8de4-435a727a559f.png)
�

2021-12-01 18:06 UTC, jamiek-acl commented on packages/ButtonGroup/stories/Example.js
> +const Example = ({ itemData, isDisabled, ...rest }) => (
we typically call it `moreProps` not `rest`, but no biggie in a story

2021-12-01 18:06 UTC, jamiek-acl approved these changes

2021-12-01 18:08 UTC, jamiek-acl commented on packages/ButtonGroup/stories/ButtonGroup.stories.js
> +import React from "react";
This is not used; eslint error

2021-12-01 18:08 UTC, jamiek-acl requested changes
eslint error

2021-12-01 18:53 UTC, AndreyChernykh commented
LGTM 
I guess we can approve it as soon as @jamiek-acl 's comments are addressed

2021-12-06 18:44 UTC, jamiek-acl approved these changes

2021-12-06 19:21 UTC, merged