UXD-316 DataGrid & Table zebra order
acl-services/paprika pull request #740
Opened 2020-10-02 23:37 UTC by KDarcey

### Purpose 🚀
To align DataGrid and Table designs with the designs in the Figma Starling UI Kit.

### Notes ✏️
- Re-arranged the zebra pattern on DataGrid 
- Changed default borders for the Table component

### Updates 📦
- [ ] MAJOR (breaking) change to _these packages_
- [ ] MINOR (backward compatible) change to _these packages_
- [x] PATCH (bug fix) change to _these packages_

### Storybook 📕
http://storybooks.highbond-s3.com/paprika/UXD-316-DataGrid-Table-zebra-order

### Screenshots 📸
DataGrid Before:
![image](https://user-images.githubusercontent.com/67071090/94977252-d054f400-04cc-11eb-8dfd-59f8b035ab40.png)

DataGrid After:
![image](https://user-images.githubusercontent.com/67071090/94977386-5e30df00-04cd-11eb-8f1f-f50b91b4a211.png)

Table Before:
![image](https://user-images.githubusercontent.com/67071090/94977407-7274dc00-04cd-11eb-936e-65a451198c0b.png)

Table After:
![image](https://user-images.githubusercontent.com/67071090/94977421-802a6180-04cd-11eb-9c4f-a4661a0b36cd.png)

### References 🔗
https://aclgrc.atlassian.net/browse/UXD-316

2020-10-02 23:45 UTC, sunminsarahlee commented
@KaanDarcey Table Vertical should have horizontal line as well like grid default value one. 
![Screen Shot 2020-10-02 at 4 44 07 PM](https://user-images.githubusercontent.com/20195302/94977664-9389fc80-04ce-11eb-8c40-a23db85b32f9.png)

2020-10-02 23:54 UTC, nahumzs approved these changes

2020-10-02 23:57 UTC, nahumzs requested changes
This a breaking change since the table default is not longer Grid, can you add a changelog?

2020-10-05 17:51 UTC, nahumzs approved these changes

2020-10-05 17:51 UTC, merged